fix(siwe): fix session checks and call onSignIn for 1CA
reown-com/appkit pull request #2507
Opened 2024-07-04 07:58 UTC by Cali93

# Description

- Fixes a bug where `onSignIn` wasn't called in the 1CA flow.
- Sets the session state upon successful signature verification.
- `onNewAddress` improvements
  - Fixes session checks as the session can be an empty object resulting in always being truthy.
  - Checks against the address in the current session, which is more reliable than `previousAddress` state variable.
- Fixes a bug where closing the modal would disconnect the user.

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

# Checklist

- [X] Code in this PR is covered by automated tests (Unit tests, E2E tests)
- [X] My changes generate no new warnings
- [X] I have reviewed my own code
- [X] I have filled out all required sections

2024-07-04 12:22 UTC, tomiir approved these changes

2024-07-04 13:14 UTC, ganchoradkov approved these changes

2024-08-05 14:34 UTC, ignaciosantise commented
What happened with this? @Cali93 @tomiir

2024-08-05 14:54 UTC, ignaciosantise requested changes

2024-08-05 14:54 UTC, ignaciosantise commented on packages/scaffold-ui/src/modal/w3m-modal/index.ts
> +      if (!session?.address || !session?.chainId) {
@Cali93 i think this will cause issues. If the user connects to a wallet and refreshes the dapp before signing, the sign popup won't appear again

2024-08-05 14:54 UTC, ignaciosantise commented on packages/scaffold-ui/src/modal/w3m-modal/index.ts
> +      if (!session?.address || !session?.chainId) {
https://github.com/user-attachments/assets/9b943f48-9dea-4686-a8a4-6f1ec1e1f113

2024-10-03 14:56 UTC, lukaisailovic commented
@Cali93 Should we merge this or close it?

2024-12-09 12:48 UTC, closed without merging